Added italian translation
santisoler/cc-licenses pull request #14
Opened 2021-04-24 12:35 UTC by Magicianred

Added a new it folder containing a README.md file that is a translation of the English README.md.
Added the Italian version of the license texts (convert the html version of the creative commons website).
Added a badge on the main README.md pointing to the Italian translation folder.
Added a badge on it/README.md pointing to the main README.md.

I hope the formatting of the plain text of the licence is pretty good :) If not, I try to correct it

Thanks

2021-04-26 03:47 UTC, vaporwavy commented
I don't know Italian, but the formatting seems good!

2021-04-27 23:12 UTC, santisoler requested changes
Thanks @Magicianred for this awesome work!
I left some minor suggestions, they might seem a lot but they're mostly the same suggestion repeated on every appearance of the same text, so don't worry.

One more thing, since #10 has been merged, would you like to add a translation and its entry to the `README.md`? If I'm asking too much, we can merge this PR first, and take care of this extra addition later.

Thanks again for the contribution!

2021-04-27 23:12 UTC, santisoler commented on it/README.md
> +* [Creative Commons Attribution 4.0 International](#cc-attribution-40-international)
I think the names of the licenses should be also translated following the translation made by CC.
```suggestion
* [Creative Commons Attribuzione 4.0 Internazionale](#cc-attribution-40-international)
```

2021-04-27 23:12 UTC, santisoler commented on it/README.md
> +* [Creative Commons Attribution-ShareAlike 4.0 International](#cc-attribution-sharealike-40-international)
```suggestion
* [Creative Commons Attribuzione - Condividi allo stesso modo 4.0 Internazionale](#cc-attribution-sharealike-40-international)
```

2021-04-27 23:12 UTC, santisoler commented on it/README.md
> +## CC Attribution 4.0 International
```suggestion
## CC Attribuzione 4.0 Internazionale
```

2021-04-27 23:12 UTC, santisoler commented on it/README.md
> +## CC Attribution-ShareAlike 4.0 International
```suggestion
## CC Attribuzione - Condividi allo stesso modo 4.0 Internazionale
```

2021-04-27 23:12 UTC, santisoler commented on it/README.md
> +[Creative Commons Attribution 4.0 International License][cc-by].
Could you translate these sentence also? Remember to change the name of the license

2021-04-27 23:12 UTC, santisoler commented on it/README.md
> +[Creative Commons Attribution 4.0 International License][cc-by].
Same here

2021-04-27 23:12 UTC, santisoler commented on it/README.md
> +[Creative Commons Attribution-ShareAlike 4.0 International License][cc-by-sa].
Same here

2021-04-27 23:12 UTC, santisoler commented on it/README.md
> +International License][cc-by-sa].
Same here

2021-04-27 23:12 UTC, santisoler commented on it/README.md
> +[cc-by]: http://creativecommons.org/licenses/by/4.0/
Would be nice that these links point to the Italian translated websites of CC:
```suggestion
[cc-by]: http://creativecommons.org/licenses/by/4.0/deed.it
```

2021-04-27 23:12 UTC, santisoler commented on it/README.md
> +[cc-by]: http://creativecommons.org/licenses/by/4.0/
```suggestion
[cc-by]: http://creativecommons.org/licenses/by/4.0/deed.it
```

2021-04-27 23:12 UTC, santisoler commented on it/README.md
> +[cc-by-sa]: http://creativecommons.org/licenses/by-sa/4.0/
```suggestion
[cc-by-sa]: http://creativecommons.org/licenses/by-sa/4.0/deed.it
```

2021-04-27 23:12 UTC, santisoler commented on it/README.md
> +[cc-by-sa]: http://creativecommons.org/licenses/by-sa/4.0/
```suggestion
[cc-by-sa]: http://creativecommons.org/licenses/by-sa/4.0/deed.it
```

2021-05-02 08:40 UTC, Magicianred commented
I made all changes and I added the cc-by-nc-sa in italian :)
Thanks :)

2021-05-04 14:05 UTC, santisoler requested changes
Again, awesome work @Magicianred  !

I just noticed that the link in the `README.md` to the following sections were broken. I left some suggestion to fix them, but they need to checked, high change of being broken too 😬 

Besides that, I think this PR should be ready to be merged.
Thanks again for your time!

2021-05-04 14:05 UTC, santisoler commented on it/README.md
> +* [Creative Commons Attribuzione 4.0 Internazionale](#cc-attribution-40-international)
```suggestion
* [Creative Commons Attribuzione 4.0 Internazionale](#cc-attribuzione-40-internazionale)
```

2021-05-04 14:05 UTC, santisoler commented on it/README.md
> +* [Creative Commons Attribuzione - Condividi allo stesso modo 4.0 Internazionale](#cc-attribution-sharealike-40-international)
```suggestion
* [Creative Commons Attribuzione - Condividi allo stesso modo 4.0 Internazionale](#cc-attribuzione-condividi-allo-stesso-modo-40-internazionale)
```

2021-05-04 14:05 UTC, santisoler commented on it/README.md
> +* [Creative Commons Attribuzione - Non commerciale - Condividi allo stesso modo 4.0 Internazionale](#cc-attribution-noncommercial-sharealike-40-international)
```suggestion
* [Creative Commons Attribuzione - Non commerciale - Condividi allo stesso modo 4.0 Internazionale](#cc-attribuzione-non-commerciale-condividi-allo-stesso-modo-40-internazionale)
```

2021-05-06 05:48 UTC, Magicianred commented
thanks, i didn't notice
I have now fixed the links :)

2021-05-07 12:23 UTC, santisoler commented
Awesome @Magicianred ! Thanks again for the contribution.

I'm updating this branch and merging it! 🎉  🚀 🏅

2021-05-07 12:24 UTC, santisoler approved these changes

2021-05-07 12:24 UTC, merged

2021-05-07 17:20 UTC, Magicianred commented
Thanks you too :)