Add spanish README
santisoler/cc-licenses pull request #6
Opened 2020-07-06 23:06 UTC by frxncismor

Linked to #3.

I finished converting the Spanish translations of the README.

2020-07-07 06:27 UTC, cyb3rko commented
If you take a look at my German README you can see the badge at the top, which leads you back to the root, maybe you should include it as well. If you need help, I'm there.

2020-07-07 18:31 UTC, santisoler requested changes
Thank you very much @frxncismor!

I leave some small modifications:
- Use a non-formal Spanish,
- Modify suggested text according to the deeds from Creative Commons.

Please, take a look at them when you have time.

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +en repositorios Github a través del lenguaje Markdown.
```suggestion
en repositorios de Github a través del lenguaje Markdown.
```

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +> No debería usar licencias Creative Commons para software.
```suggestion
> No debes utilizar licencias Creative Commons para software.
```

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +* [Creative Commons Atribución/Reconocimiento 4.0 Internacional](#cc-attribution-40-international)
Creative Commons use a shorter version of the license name on [their instruction deeds](https://creativecommons.org/licenses/by/4.0/deed.es): _Creative Commons Atribución 4.0 Internacional_. So, we might want to do the same in order to keep things simpler.
Besides, the link won't work as it is, so I changed that too.
```suggestion
* [Creative Commons Atribución 4.0 Internacional](#cc-atribución-40-internacional)
```

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +* [Creative Commons Atribución/Reconocimiento-CompartirIgual 4.0](#cc-attribution-sharealike-40-international)
```suggestion
* [Creative Commons Atribución-CompartirIgual 4.0](#cc-atribución-compartirigual-40-internacional)
```

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +## Creative Commons Atribución/Reconocimiento 4.0 Internacional
```suggestion
## CC Atribución 4.0 Internacional
```

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +Este trabajo está licenciado bajo [Creative Commons Atribución/Reconocimiento 4.0 Internacional][cc-by].
El [deed de la licencia](https://creativecommons.org/choose/?lang=es_AR) recomienda utilizar este texto en español:

```suggestion
Esta obra está bajo una [Licencia Creative Commons Atribución 4.0 Internacional][cc-by].
```

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +## Creative Commons Atribución/Reconocimiento-CompartirIgual 4.0
```suggestion
## CC Atribución-CompartirIgual 4.0

```

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +[Creative Commons Atribución/Reconocimiento-CompartirIgual 4.0][cc-by-sa].
```suggestion
Esta obra está bajo una [Licencia Creative Commons Atribución-CompartirIgual 4.0 Internacional][cc-by-sa].
```

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +Este trabajo está licenciado bajo [Creative Commons Atribución/Reconocimiento-CompartirIgual 4.0][cc-by-sa].
```suggestion
Esta obra está bajo una [Licencia Creative Commons Atribución-CompartirIgual 4.0 Internacional][cc-by-sa].
```

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +Se puede obtener más información sobre licencias y textos de licencias con formato de texto sin formato
```suggestion
Puedes obtener más información sobre licencias y textos de licencias con formato de texto plano
```

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +Para agregar una licencia CC BY a su proyecto, simplemente agregue lo siguiente a su
```suggestion
Para agregar una licencia CC BY a tu proyecto, simplemente agrega lo siguiente a tu
```

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +`README.md`. También debe copiar el [archivo de texto](LICENSE-CC-BY) de la licencia correspondiente y
```suggestion
`README.md`. También debes copiar el [archivo de texto](LICENSE-CC-BY) de la licencia correspondiente y 
```

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +Para agregar una licencia CC BY-SA a su proyecto, simplemente agregue lo siguiente a su
```suggestion
Para agregar una licencia CC BY-SA a tu proyecto, simplemente agrega lo siguiente a tu
```

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +`README.md`. También debe copiar el [archivo de texto](LICENSE-CC-BY-SA) de la licencia correspondiente y
```suggestion
`README.md`. También debes copiar el [archivo de texto](LICENSE-CC-BY-SA) de la licencia correspondiente y 
```

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +La manera más facil de encontrar la licencia CC adecuada para su proyecto es en el
```suggestion
La manera más facil de encontrar la licencia CC adecuada para tu proyecto es en el
```

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +Aqui le presentamos dos tipos de licencias CC:
```suggestion
Aquí te presentamos dos tipos de licencias CC:
```

2020-07-07 18:31 UTC, santisoler commented on es/README.md
> +y otras por favor visite https://creativecommons.org/about/downloads/.
```suggestion
Si quieres descargar la versión vectorizada de las imagenes de Creative Commons
y otras, por favor visita https://creativecommons.org/about/downloads/.
```

2020-07-07 18:55 UTC, frxncismor commented
Ok i read all of your comments guys and i fixed the errors, hope i did well this time. I'm sorry it's my first contribution to open source

2020-07-07 20:13 UTC, cyb3rko commented
@frxncismor @santisoler One more question for all of us:
Do we wanna add the original name of the licenses in the translated READMEs or do you think that it's unnecessary?

<img src="https://user-images.githubusercontent.com/46033730/86837212-dfc7cb00-c09e-11ea-945b-73b04f960b7f.png" width = "750">

2020-07-08 04:12 UTC, frxncismor commented
I think it's unnecessary because that information is on the main language

2020-07-08 07:49 UTC, cyb3rko commented
Ok, then I will rework the German translation and yours is perfect!

2020-07-09 00:06 UTC, santisoler requested changes
Thanks @frxncismor for the modifications!

I leave some small changes, like missing tildes and an exact copy of the text proposed by Creative Commons. I think after you commit these changes we might be ready to merge!

2020-07-09 00:06 UTC, santisoler commented on es/README.md
> +La manera más facil de encontrar la licencia CC adecuada para tu proyecto es en el
```suggestion
La manera más fácil de encontrar la licencia CC adecuada para tu proyecto es en el
```

2020-07-09 00:06 UTC, santisoler commented on es/README.md
> +Aqui te presentamos dos tipos de licencias CC:
```suggestion
Aquí te presentamos dos tipos de licencias CC:
```

2020-07-09 00:06 UTC, santisoler commented on es/README.md
> +Puedes obtener más información sobre licencias y textos de licencias con formato de texto plano
```suggestion
Puedes obtener más información sobre licencias y sus textos completos en texto plano
```

2020-07-09 00:06 UTC, santisoler commented on es/README.md
> +Este trabajo está licenciado bajo [Licencia Creative Commons Atribución 4.0 Internacional][cc-by].
```suggestion
Esta obra está bajo una [Licencia Creative Commons Atribución 4.0 Internacional][cc-by].
```

2020-07-09 00:06 UTC, santisoler commented on es/README.md
> +Este trabajo está licenciado bajo [Licencia Creative Commons Atribución 4.0 Internacional][cc-by].
```suggestion
Esta obra está bajo una [Licencia Creative Commons Atribución 4.0 Internacional][cc-by].
```

2020-07-09 00:06 UTC, santisoler commented on es/README.md
> +Este trabajo está licenciado bajo
```suggestion
Esta obra está bajo una
```

2020-07-09 00:06 UTC, santisoler commented on es/README.md
> +Este trabajo está licenciado bajo [ Licencia Creative Commons Atribución-CompartirIgual 4.0 Internacional][cc-by-sa].
```suggestion
Esta obra está bajo una
[Licencia Creative Commons Atribución-CompartirIgual 4.0 Internacional][cc-by-sa].
```

2020-07-09 00:47 UTC, frxncismor commented
I think it's done, please review it and thank you for give me the opportunity to contribute

2020-07-09 14:01 UTC, santisoler approved these changes

2020-07-09 14:07 UTC, santisoler commented
Thanks a lot of tackling this @frxncismor!
I'll merge it right away.

I've just seen that you open this PR from the `master` branch of your fork.
As I told @cyb3rko on #2, your `master` will diverge from mine after I merge this. The easier way to solve it is to just delete your fork and refork it again if you want. But they way to prevent this is to create a branch where all your new commits will leave and then open the PR from that branch.
For example, @cyb3rko opened #5 from them `spanish` branch.
The good notice is that it's hard to break things in git and GitHub that aren't easily solved, so no big deal.

Thanks again for the contribution!

2020-07-09 14:09 UTC, merged